config/routes.rb
Rails.application.routes.draw do
  root to: 'searches#index'

  # remove 'searches/' from url since it's our only route
  resources :searches, path: '', only: %w(index create)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :search_term, touch: true, counter_cache: true
end

app/models/search_term.rb
class SearchTerm < ApplicationRecord
  has_many :searches, dependent: :destroy

  validates :query, presence: true, uniqueness: true

  # Scope to filter past search history
  def self.filter_query(filter_by)
    if filter_by.present?
      case filter_by
      when 'alphabetical'
        order(query: :asc)
      when 'order-asc'
        order(updated_at: :asc)
      when 'order-desc'
        order(updated_at: :desc)
      when 'count'
        order(searches_count: :desc)
      else
        none # They probably put something that didn't match our filter params
      end
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action(:set_facade)

  def index
    # If the user visits the index with the search param, we want to treat it
    # as if they submitted the search form, and record it as a new search for
    # that.
    Search.create(search_term: search_term) unless params[:search].blank?
  end

  def create
    Search.create(search_term: search_term) unless params[:search].blank?
    render :index
  end

  private

  def search_term
    SearchTerm.find_or_create_by(query: params[:search])
  end

  def set_facade
    @facade = SearchFacade.new(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def options_for_search_history_filter(selected = nil)
    options_for_select(
      [
        ['Alphabetical', 'alphabetical'],
        ['Recent search (ASC)', 'order-asc'],
        ['Recent search (DESC)', 'order-desc'],
        ['Highest Searched', 'count']
      ],
      selected
    )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nasa Images API</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/searches/index.html.erb
<h2>Search NASA.gov Images</h2>

<p>
  Enter in your search param to search the Nasa Images API
</p>

<hr>

<div class="row">
  <div class="col-md-3">
  <%= form_tag(searches_path, method: :post) do |f| %>
    <%= text_field_tag :search, params[:search], placeholder: 'Try: mars' %>
    <%= select_tag "filter_by",
      options_for_search_history_filter(params[:filter_by]),
      prompt: "Filter History" %>
    <%= submit_tag "Search" %>
  <% end %>

    <h4>Previous Searches:</h4>
    <% @facade.previous_searches.each do |term| %>
      <li>
        [<%= term.searches_count %>]
        <%= link_to term.query, searches_path(search: term.query,
          filter_by: params[:filter_by]) %>
      </li>
    <% end %>

    <hr />
    <% if @facade.search_activity.any? %>
      <h5>Previous Searches for <%= params[:search] %></h5>
      <% @facade.search_activity.each do |search| %>
        <%= search.created_at %><br />
      <% end %>
    <% end %>
  </div>

  <div class="col-md-9">
    <% if @facade.results.present? %>
      <div class="card card-body">
        <!-- A followup thing I would do here is
         actually render the results after parsing it -->
        <%= @facade.results %>
      </div>
    <% else %>
      No results found, try searching :)
    <% end  %>
  </div>
</div>